### PR TITLE
centre: rpi netboot cleanup

### PR DESCRIPTION
**Pull request by pmazzini**
Follow up of https://github.com/insomniacslk/dhcp/issues/405.

The BSDP package has Apple extensions of the dhcpv4 protocol, I don't think it should be used here.

This code should do what is expected here but I don't have the proper test environment.

### CODE REVIEW

**Review by rminnich — CHANGES_REQUESTED** [review]
Was this tested? And what if the environment is a mixed rpi/non-rpi? I just now noticed the -raspi switch which seems like a problem to me. This seems to compound that problem, since it seems we can't have mixed rpi/non-rpi networks?

**Comment by rminnich** [comment]
the --raspi switch is marked for death, so we don't want to compound that mistake by using it elsewhere. But thanks!

**Review by rminnich — CHANGES_REQUESTED** [review]
we don't want to add more dependencies to the raspi switch, since it was a mistake in the first place.

**Comment by pmazzini** [comment]
> the --raspi switch is marked for death

Shall I put up a PR to remove it?

**Pull request closed without merging**
