### PR TITLE
syslinux: remove program

### PR DESCRIPTION
**Pull request by fhs**
This program was copied from the havey repo (commit
21c522a373f94bff5addfc84d37c35fe58f01bfd) and has hardcoded paths to
files from that repo.  The
[wiki](https://github.com/Harvey-OS/harvey/wiki/Booting-Harvey-on-real-hardware-II-(USB))
refers to this program but it no longer works unless you are in the
right directory.

Helps https://github.com/Harvey-OS/harvey/issues/1072

Signed-off-by: Fazlul Shahriar <fshahriar@gmail.com>

### CODE REVIEW

**Comment by gmacd** [comment]
Why remove the program?  Is there a way to fix it instead?

**Comment by fhs** [comment]
> Why remove the program? Is there a way to fix it instead?

I thought we don't need this program anymore since harvey's `util/build-image.sh` script does the same thing but doesn't require root access. If we really want to keep it, maybe it can require `$HARVEY` environment variable (or a flag) and use that as the prefix to all the paths.

**Comment by sevki** [comment]
@gmacd do we need it?

**Comment by gmacd** [comment]
@rminnich wrote this as a standalone, dependency-free way of creating an image.
I wrote the build-img.sh script as a way to build without root, but with the dependency of guestfish from libguest.

I think both are out of date.  If we build an image using uroot in a ramdisk, we don't need anything other than a fat32 image with the kernel and hopefully a ramdisk.

**Comment by fhs** [comment]
I guess it's worth keeping for now? I'll see if I can make it more usable. The guestfish approach isn't as portable as I initially thought.

**Pull request closed without merging**
